#!/usr/bin/env bash

alias love="\"/mnt/c/Program Files/LOVE/lovec.exe\""
alias subl="\"/mnt/c/Program Files/Sublime Text 3/sublime_text.exe\""
alias gita="git add -A"
alias gitc="git commit -m"
alias gitd="git diff"
alias gitds="git diff --staged"
alias gitl="git log --graph --oneline --decorate --all"
alias gitp="git push"
alias gits="git status"
alias cls="clear"
alias hl="highlight -O truecolor --style=github"
alias cath="highlight $1 -O truecolor --style=github"
alias diff="diff --color"
alias startssh="eval \$(ssh-agent -s) && ssh-add"
alias lua="lua5.3"
